---
apiVersion: batch/v1
kind: Job
metadata:
  name: quay-s3-credentials-setup
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  template:
    spec:
      serviceAccountName: quay-s3-setup
      containers:
      - name: setup-s3-credentials
        image: registry.redhat.io/openshift4/ose-cli:latest
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Setting up S3 credentials for Quay from NooBaa MOG ObjectBucketClaim..."
          
          echo "Using oc for Kubernetes API access..."
          
          # Check if ObjectBucketClaim exists and is bound
          echo "Checking ObjectBucketClaim quay-bucket status..."
          oc get objectbucketclaim quay-bucket -n openshift-storage
          
          # Wait for ObjectBucketClaim to be in Bound state
          echo "Waiting for ObjectBucketClaim quay-bucket to be Bound (timeout: 10 minutes)..."
          oc wait --for=jsonpath='{.status.phase}'=Bound objectbucketclaim/quay-bucket -n openshift-storage --timeout=600s || {
            echo "ERROR: ObjectBucketClaim failed to reach Bound state within timeout"
            oc describe objectbucketclaim quay-bucket -n openshift-storage
            exit 1
          }
          
          # Use the actual secret and configmap names (not the objectBucketName from spec)
          CONFIG_MAP="quay-bucket"
          SECRET_NAME="quay-bucket"
          
          echo "ConfigMap: $CONFIG_MAP"
          echo "Secret: $SECRET_NAME"
          
          # Extract S3 credentials
          ACCESS_KEY=$(oc get secret $SECRET_NAME -n openshift-storage -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)
          SECRET_KEY=$(oc get secret $SECRET_NAME -n openshift-storage -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)
          BUCKET_NAME=$(oc get configmap $CONFIG_MAP -n openshift-storage -o jsonpath='{.data.BUCKET_NAME}')
          S3_ENDPOINT=$(oc get configmap $CONFIG_MAP -n openshift-storage -o jsonpath='{.data.BUCKET_HOST}')
          
          echo "Retrieved S3 credentials successfully"
          echo "Bucket: $BUCKET_NAME"
          echo "Endpoint: $S3_ENDPOINT"
          
          # Get current Quay config secret
          oc get secret {{ .Values.quay.configBundleSecret.name }} -n {{ .Values.quay.namespace }} -o jsonpath='{.data.config\.yaml}' | base64 -d > /tmp/config.yaml
          
          # Replace placeholders with actual values using a different delimiter to handle special characters
          sed -i "s|PLACEHOLDER_ACCESS_KEY|$ACCESS_KEY|g" /tmp/config.yaml
          sed -i "s|PLACEHOLDER_SECRET_KEY|$SECRET_KEY|g" /tmp/config.yaml
          sed -i "s|PLACEHOLDER_BUCKET_NAME|$BUCKET_NAME|g" /tmp/config.yaml
          
          # Encode config as base64 for patching
          CONFIG_BASE64=$(base64 -w 0 /tmp/config.yaml)
          
          # Patch the secret data field directly
          oc patch secret {{ .Values.quay.configBundleSecret.name }} -n {{ .Values.quay.namespace }} \
            --type='json' \
            -p="[{'op': 'replace', 'path': '/data/config.yaml', 'value': '$CONFIG_BASE64'}]"
          
          echo "Quay S3 credentials setup completed successfully"
      restartPolicy: OnFailure
  backoffLimit: 5
