{{- if .Values.certmgrOperator.issuers.acme }}
{{- if or .Values.certmgrOperator.issuers.acme.aws .Values.certmgrOperator.issuers.acme.azure .Values.certmgrOperator.issuers.acme.gcp }}
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: cert-manager-credentials-request
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.certmgrOperator.issuers.acme.aws }}
  secretRef:
    name: aws-credentials
    namespace: {{ .Release.Namespace }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - route53:GetChange
      - route53:ChangeResourceRecordSets
      - route53:ListHostedZonesByName
      resource:
      - arn:aws:route53:::hostedzone/*
    - effect: Allow
      action:
      - route53:ListHostedZones
      resource:
      - "*"
{{- end }}
{{- if .Values.certmgrOperator.issuers.acme.azure }}
  secretRef:
    name: azure-credentials
    namespace: {{ .Release.Namespace }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    roleBindings:
    - role: "DNS Zone Contributor"
{{- end }}
{{- if .Values.certmgrOperator.issuers.acme.gcp }}
  secretRef:
    name: gcp-credentials
    namespace: {{ .Release.Namespace }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
    - "roles/dns.admin"
    gcpServiceAccount: "cert-manager-{{ .Values.global.clusterName }}-dns"
{{- end }}
{{- end }}
{{- end }}