---
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: {{ .Values.noobaa.system.name }}
  namespace: {{ .Values.noobaa.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  tolerations:
    - key: "node.ocs.openshift.io/storage"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
