---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: image-registry-credentials
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: image-registry-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson }}` }}"
  data:
  - secretKey: dockerconfigjson
    remoteRef:
      key: {{ .Values.quay.vaultPath }}
      property: dockerconfigjson