---
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: {{ .Values.noobaa.system.name }}
  namespace: {{ .Values.noobaa.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Layer 1: Deploy NooBaa System
spec:
  tolerations:
    - key: "node.ocs.openshift.io/storage"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  pvPool:
    resources:
      requests:
        cpu: {{ .Values.noobaa.pvPool.resources.requests.cpu }}
        memory: {{ .Values.noobaa.pvPool.resources.requests.memory }}
        storage: {{ .Values.noobaa.pvPool.resources.requests.storage }}
      limits:
        cpu: {{ .Values.noobaa.pvPool.resources.limits.cpu }}
        memory: {{ .Values.noobaa.pvPool.resources.limits.memory }}
  dbVolumeResources:
    requests:
      storage: {{ .Values.noobaa.dbSize }}