{{- if and .Values.enabled .Values.loki.enabled }}
{{- $storageClass := .Values.loki.storageClassName }}
{{- if not $storageClass }}
  {{- range $sc := (lookup "storage.k8s.io/v1" "StorageClass" "" "").items }}
    {{- if eq (index $sc.metadata.annotations "storageclass.kubernetes.io/is-default-class") "true" }}
      {{- $storageClass = $sc.metadata.name }}
    {{- end }}
  {{- end }}
{{- end }}
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: {{ .Values.loki.name }}
  namespace: {{ .Values.loki.namespace }}
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "41"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  size: {{ .Values.loki.size }}
  storageClassName: {{ $storageClass }}
  storage:
    schemas:
      - version: v13
        effectiveDate: "2022-06-01"
    secret:
      name: {{ .Values.loki.storageSecretName }}
      type: s3
  tenants:
    mode: openshift-network
{{- end }}
